function trackers=configTrackers


trackers = {
            struct('name','OURS_CNN_4_4', 'namePaper', 'OURS_CNN_12'),...
            struct('name','OURS', 'namePaper', 'OURS_HOG'),...    
            struct('name','MDNET','namePaper','MDNET'),...
            struct('name','CF2', 'namePaper', 'CF2'),... 
            struct('name','KCF','namePaper','KCF_HOG'),...                        
            struct('name','ASMS','namePaper','ASMS'),...       
            struct('name','DSST','namePaper','DSST'),...        
            struct('name','MEEM','namePaper','MEEM'),...       
            struct('name','SRDCF','namePaper','SRDCF'),...     
            struct('name','MUSTer','namePaper','MUSTer')    
};

       
% trackers = {
%              struct('name','KCF','namePaper','KCF_HOG'),...   
%              struct('name','KCF_raw','namePaper','KCF_RAW'),... 
%              struct('name','KCF_CNN_3_4','namePaper','KCF_CNN_8'),...
%              struct('name','KCF_CNN_4_4','namePaper','KCF_CNN_12'),...
%              struct('name','KCF_CNN_5_4','namePaper','KCF_CNN_16'),...             
% };
% 
% trackers = {
%              struct('name','KCF_raw','namePaper','KCF_RAW'),...
%              struct('name','KCF_CNN_4_4','namePaper','KCF_CNN_12'),... 
%              struct('name','OURS_raw', 'namePaper', 'OURS_RAW'),...
%              struct('name','OURS_CNN_4_4', 'namePaper', 'OURS_CNN_12')
% };
